### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by MiLk** [payutc/server#125]
Suite à une remarque de John, je me suis intéressé aux transactions sur PayUTC.
Il semble qu'il en manque quelques unes non critiques liées à l'intégrité des données.

N'ayant aucune connaissance du fonctionnement du serveur certaines remarques ne sont peut-être pas pertinentes.

https://github.com/payutc/server/blob/master/class/Buy.class.php#L134
Un UPDATE suivi d'un INSERT.
Si l'INSERT échoue, l'utilisateur sera modifié sans garder de trace.

https://github.com/payutc/server/blob/master/class/Buyer.class.php#L114
N SELECT+UPDATE suivi d'un UPDATE.
Et si le panier était vidé sans recréditer l'utilisateur ?

Je n'ai jetté qu'un coup d'oeil aux classes, mais si dans le controleur plusieurs méthodes des modèles sont appelées, de manière à faire un UPDATE/INSERT sur  les 2 requêtes et/ou utiliser le résultat de la première dans la deuxieme.
Il faut faire une transaction.

**Comment by mattgu74** [comment]
Je dirais que ça va avec #66

**Comment by apuyou** [comment]
Le code que tu cites n'est actuellement pas utilisé, mais on a effectivement quelques soucis transactionnels à ce niveau là : https://github.com/payutc/server/blob/master/src/Payutc/Service/POSS2.php#L360

Je penserai à mettre des méthodes pour gérer des transactions au moment de faire la surcouche à PDO. Mais il faut quand même garder cette issue pour penser à vérifier qu'il n'y a pas de soucis ailleurs.

**Comment by mattgu74** [comment]
Des transactions ont été mises partout ou c'est critique (et même ailleurs).
Je ne pense pas que garder cette issue ouverte soit utile.
