### ISSUE TITLE
Remove unused methods in User

### ISSUE THREAD

**Issue by trecouvr** [payutc/server#126]
- hasDroit
- isSeller

**Comment by mattgu74** [comment]
dans payutc non, mais dans buckutt oui... Au début on avais décidé de conserver la compatibilité avec eux, mais bon la on est partie tellement loin, qu'effectivement je pense qu'on va pouvoir prendre la décision de jarter tout ce qui concerne buckutt exclusivement.

**Comment by apuyou** [comment]
Done in #216
