### ISSUE TITLE
Put Configuration in an autoload Class

### ISSUE THREAD

**Issue by trecouvr** [payutc/server#134]

**Comment by apuyou** [comment]
En fait, pour détailler un peu, la config est actuellement dans une variable globale qui est pas terrible à utiliser.

Il faut faire une classe statique qui permet d'accéder à la config et est chargée par l'autoloader (du style \Payutc\Config tout simplement).

**Comment by trecouvr** [comment]
En fait, plus que de la mettre dans une classe et de faire des autoload, faudrait la supprimer de toutes nos classes, c'est dégueux de mélanger de la config à des méthodes de classes, ce que t'as besoin de la config tu le files au constructeur de ta classe...
Après autoload c'est du bonus mais ça devrait même pas être le problème principal.
De mon point de vu les seules classes qui devraient utiliser la config sont les services.
