### ISSUE TITLE
Blocage d'utilisateur par fundation

### ISSUE THREAD

**Issue by apuyou** [payutc/server#14]
Il faut pouvoir empêcher l'accès à une fondation à un utilisateur spécifique.

Supprimer les mol n'est pas une bonne idée (le compte est recréé automatiquement).

**Comment by mattgu74** [comment]
Petit UP, j'attribue ça a la milestones "FIN P13".
C'est URGENT.

Il faut rédiger 3 sous-taches:
- server => Création de la db et des classes correspondantes
- server => Exposition du service (réfléchir, est-ce un service indépendant ou à coupler dans AADMIN ?)
     Je dirais que c'est un service à part, car c'est un droit différent (le droit de bloquer)
- scoobydoo => Intégrer un module pour gérer ce service

**Comment by mattgu74** [comment]
Enfait c'est plus qu'urgent faudrait envisager ça pour ce weekend.
Je propose d'utiliser les tables groupes qu'on avait shunter mais qui existe toujours.

On pourrait faire un groupe par fondation "<fundation_name>_BANNED".
Et les méthodes qui vont bien pour bloquer/débloquer (qui créerait le groupe dynamiquement quand il n'existe pas)

Du coup dans Buy.class.php faudra tester à l'achat si le mec est BANNED ou non pour la fundation donné.

Et ensuite ajouter une interface dans scoobydoo. Je propose de faire un service specifique au blocage/déblocage (ce qui permet d'ajouter un nouveau droit, le droit de "bloqueur") et ce service pourrait être le premier à utiliser mon nouveau système de gestions des droits.

ROADMAP validé ? Si oui, il faut créer les tickets qui vont bien et me les assigner et je peux faire tourner ça pour la fin du weekend.

**Comment by apuyou** [comment]
Perso je préfère une nouvelle table dédiée à ça, pour ne pas changer la façon d'utiliser les tables existantes.

**Comment by mattgu74** [comment]
Taches à venir
- [x] créer la table `tj_usr_fun_blocked_blo` (`blo_id(int autoincrement)` et `usr_id(int)` et `fun_id(int NULL)` et `blo_raison (varchar)` et `blo_insert(datetime)` et `blo_removed(datetime)`)
- [x] créer la classe Blocked (Tout la partie "sql")
- [x] appeler Banned depuis les endroits ou l'ont fait des ventes
- [x] créer le service Blocked
- [x] scoobydoo ajouter un module pour gérer les blocages

**Comment by trecouvr** [comment]
ouai je viens de me sourvenir Margo m'en a reparlé, en plus apparement avant y'avait un bug, quand le mec se faisait ban, puis re-allait sur payutc (casper) il pouvait réouvrir un compte et regagner sa thune de l'ancien semestre...

**Comment by trecouvr** [comment]
- Je valide la table, par contre est-ce que on pourrait faire attention à standardiser le nom des datetime pour ajout/suppression ? faudrait pas qu'on ai insert à des endroits et added ou date_insert à d'autres.
- Pour la class Blocked je pense que ça sert à rien, fais une méthode dans user.
- Le service blocked why not, je vois pas dans quel module actuel ça pourrait rentrer

**Comment by mattgu74** [comment]
Bah le service c'est un droit, après il est utilisé dans scoobydoo avec un
module pour gérer les blocages.

Tu proposes quoi comme standardisation des noms ?

Pour la classe Blocked, elle sera pas très longue, mais ça permet de rester
cohérent et de savoir ou sont définis nos requetes sql etc...
Je prefere avoir ce truc séparé de l'user enfait.

Le 23 mars 2013 20:52, Thomas Recouvreux notifications@github.com a écrit
:

**Comment by apuyou** [comment]
Hum moi je trouve que ça a du sens de mettre le contrôle de si un user est bloqué dans la classe User, ça évitera d'instancier Blocked pour ça.

On a besoin de la classe pour tout ce qui ajout/suppression de blocages par contre (donc changeons son nom : block, blocage... ?)

Arthur Puyou

**Comment by trecouvr** [comment]
Je propose added et removed, mais ça n'engage que moi.

C'est juste que je trouve plus simple de faire `$usr->isBlocked($fun)` que `Blocked::userIsBlocked($usr, $fun)`, mais encore une fois ça n'engage que moi, et rien ne t'empêche d'utiliser ta class Blocked dans la class User. D'ailleurs ça se pourrait qu'on est besoin desfois de savoir si un user est blocké sans forcément créer un objet User au préalable. Donc je dirai fais une class Blocked mais rajoutes quand même une méthode dans User :)

**Comment by apuyou** [comment]
Done in #122
