### ISSUE TITLE
Trouver un ORM léger et potable

### ISSUE THREAD

**Issue by mattgu74** [payutc/server#144]
Tout est dans le titre.

Je ne pense pas qu'on veuille d'une grosse usine à gaz.
Du coup j'ai commencé à regarder et j'ai trouvé ça:

https://github.com/j4mie/paris

Bon bien sur, faut encore chercher et écouter les propositions de tout le monde.
Je ne pense pas qu'il faille se jeter sur le premier venu, donc j'ai attaché ça à la milestone r13 qui est dans 2 mois, ça nous laisse le temps de réfléchir.

**Comment by trecouvr** [comment]
A voir si ça supporte les requetes complexes entre plusieurs tables

**Comment by trecouvr** [comment]
Je pense qu'on peut oublie idiorm et paris, domage ils avaient l'air pas mal. http://stackoverflow.com/questions/12597197/how-to-retrieve-information-from-an-association-table-using-idiorm-and-paris-wit

**Comment by apuyou** [comment]
Si vous êtes fans d'ActiveRecord, on peut tout recoder en Ruby.

----->[]

Sérieusement, avec le temps qu'on a déjà passé sur les ORM, la proposition de Thomas me paraît la moins aberrante... Avec les requêtes préparées de PDO ça nous ferait un truc simple à utiliser, performant et secure.

**Comment by trecouvr** [comment]
http://fluentpdo.com/documentation.html
http://idiorm.readthedocs.org/en/latest/querying.html
http://codehappy.daylerees.com/fluent-query-builder (laravel le retour ? xD) http://laravel.com/docs/database/fluent

Les 3 me semblent pas trop mal niveau query, c'est une syntaxe proche du sql et des retours simples.
Pour fluent PDO malheureusement y'a pas de doc pour les update/insert, je me demande même si c'est codé, domage.
Pour idiorm je pense qu'il est assez bas niveau pour permettre toutes les requetes tordues qu'on veut, il gère les update et insert en mode active record (je trouve que le mec qui a fait la lib a déconné sur ce coup là) du coup j'ai un peu peur que ça soit faible de ce côté là.
Le Fluent query builder on dirait que c'est l'ORM de laravel, il à l'air pas trop mal fait, les update et insert sont en mode sql like et pas active record. Le seul hic c'est que y'a pas l'air d'avoir de possibilité d'utiliser l'ORM sans laravel.

**Comment by trecouvr** [comment]
Yop,

Voilà mes premiers retours:
- FluentPDO semple encore en dev, pas assez de doc, pas assez connu
- idiorm ne semble pas supporter les "nested where", faire un WHERE (a AND b) OR (c AND d) c'est pas supporté, faut faire du raw_query ce qui pue.
- Fluent query builder me semble bien, mais il est pas stand alone...
- Doctrine DBAL, je vais essayer celui là, il possède un query builder, et y'a pas besoin de lui fournir le mapping ni rien http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/index.html

**Comment by mattgu74** [comment]
#147 accepted
