### ISSUE TITLE
Remove return statement in ServiceBase.class.php$checkRight

### ISSUE THREAD

**Issue by trecouvr** [payutc/server#149]
Remove useless and confusing return statement in function server/class/ServiceBase.class.php, in method checkRight.

**Comment by mattgu74** [comment]
As tu vérifié que le return était utilisé nul part dans le code ?

Parce que avant un `if($this->checkRight(...)) {`` marchait et donc il est possible qu'on en ait mis par endroit.
Même si tu as raison ça prête à confusion et ta PR est acceptable.

Mais du coup dans ce genre de cas, on fait quoi on accepte, et on réparera si ça a cassé à des endroits (ce sera l'occase de mettre des unit-tests sur ce que tu aurais potentiellement cassé) ou on est malin et on cherche d'abord tout les if qui prennent du checkRight pour les virer d'abord ? (virer les if pas les checkRight !)

**Comment by trecouvr** [comment]
J'ai fait un `git grep checkRight` j'ai vu aucun `if`. Je pense qu'on avait déjà fait gaffe avant à pas utiliser de `if`
