### ISSUE TITLE
Créer une méthode dédiée pour récupérer les dernières transactions

### ISSUE THREAD

**Issue by trecouvr** [payutc/server#157]
Les récupérer via user get infos ça pue.

**Comment by mattgu74** [comment]
Dans quel service, quel fonction ? ça se trouve ou dans quel fichier ?
:)

**Comment by trecouvr** [comment]
Peut importe ou ira cette méthode, il en faut une dédiée, actuellement c'est la fonction qui renvoie les infos sur un user qui envoie les dernière transactions (dans POSS2 en tout cas).

**Comment by mattgu74** [comment]
As tu repensé à ça dans POSS3 ?

**Comment by trecouvr** [comment]
Raaaah non j'avoue je voulais changer quelques trucs de ce cote là...

**Comment by trecouvr** [comment]
Vu que actuellement on utilise de facon tres couplée les infos de l'utilisateur avec les dernieres transactions dans Mozart et Pauline, je pense que ca sert à rien de faire une fonction dédiée.
