### ISSUE TITLE
Migration DB et redaction de la structure

### ISSUE THREAD

**Issue by mattgu74** [payutc/server#159]
@apuyou m'a parlé l'autre du jour du fait que tout comme on utilise doctrine-dbal pour construire nos requêtes.

Il existerait un composant de doctrine qui est récupérable séparément qui permettait de réaliser les migrations de DB. (Et je suppose permet d'écrire la structure de notre DB de manière plus élégantes qu'en ayant un dev_structure.sql qui traine dans le dépot)

Actuellement à chaque pull, il faut vérifier qu'il n'y a pas eu de modification (dans dev_structure.sql), et si oui les appliquer à la main...
Pouvoir en une commande appeler le composant de Doctrine qui s'occuperait de mettre à jour la DB serait juste magique.

**Comment by apuyou** [comment]
La page du projet : http://www.doctrine-project.org/projects/migrations.html

J'ai remis les migrations en état sur le portail cette semaine, c'est assez cool quand ça marche bien (ça résiste même aux branches et tout, il utilise un timestamp pour créer les numéros de versions).

**Comment by trecouvr** [comment]
On install Doctrine quoi ^^

**Comment by apuyou** [comment]
C'est done dans #220
