### ISSUE TITLE
PAYBOX vérifier pbx_auth en prod

### ISSUE THREAD

**Issue by mattgu74** [payutc/server#167]
En prod il faut s'assurer que pbx_auth != 'XXXXXX' !!!

**Comment by apuyou** [comment]
Je viens de comprendre ce que tu voulais dire par là, et ça me paraît une idée top effectivement.

Je propose d'utiliser le `PBX_SITE` plutôt que les paramètres de `slim_config` pour savoir si on est en prod ou en dev, vu que c'est lié à paybox ça devrait être suffisant (et même plus propre).

**Comment by mattgu74** [comment]
L'idée c'est d'avoir un "failback" si on oublie de configurer le pbx-site
(ou si on le configure mal) je trouve donc pas top de se baser dessus.

**Comment by apuyou** [comment]
Tu proposes quoi du coup ? Je trouve ça chiant de rajouter encore un paramètre supplémentaire.

On pourrait n'accepter les XXXXX que si le `PBX_SITE` est celui du site de test. Du coup, si tu changes la config pour mettre ton `PBX_SITE`, c'est que tu t'attends à avoir un vrai numéro d'autorisation en retour. Si le `PBX_SITE` est mauvais, je ne vois pas trop comment on pourrait le détecter (tu vas juste filer du fric à quelqu'un d'autre ^^).

**Comment by mattgu74** [comment]
C'est une première idée.
