### ISSUE TITLE
Notice sur User

### ISSUE THREAD

**Issue by apuyou** [payutc/server#169]
J'ai également ça depuis la r9 (c'est surement lié à #168) : 

```
PHP Notice:  Undefined variable: funId in /usr/share/buckutt/server/class/User.class.php on line 269
```

**Comment by mattgu74** [comment]
On attend la mise en prod, pour valider le fait que ça fixe le problème ou on peut fermer l'issue ?

**Comment by apuyou** [comment]
On fermera quand il n'y aura plus rien dans les logs.

**Comment by apuyou** [comment]
Il n'y est plus.
