### ISSUE TITLE
Implémenter la notion de semestre

### ISSUE THREAD

**Issue by apuyou** [payutc/server#180]
Il y a un TODO à cet endroit qui nécessite d'implémenter la notion de semestre (pour remplacer un switch avec des dates statiques) : https://github.com/payutc/server/pull/173/files#L1R43

Je ne sais pas si c'est vraiment nécessaire d'avoir une table, on peut effectivement calculer ça de manière assez prévisible. Genre, une fonction que j'avais faite (même si elle fait l'opération inverse) :

```
function getSemestre($time = 0){
  if(empty($time))
    $time = time();

  if(date('m', $time) == 1)
    return 'A'.(date('y', $time)-1);
  elseif(date('m', $time) >= 2 AND date('m', $time) <= 7)
    return 'P'.date('y', $time);
  elseif(date('m', $time) >= 8)
    return 'A'.date('y', $time);
  else
    return 'WTF ?';
}
```

Par contre, c'est quand même une notion très UTC. Pourquoi on ne pourrait pas demander avec les dates qu'on veut (éventuellement en mettant une période minimum de 1 mois si on veut limiter l'extraction de données) ?

**Comment by trecouvr** [comment]
+1 pour que le serveur n'implémente pas la notion de semestre. A la limite le client pourrait le gérer avec une fonction qui calcul tout seul.

**Comment by mattgu74** [comment]
Ok vous avez gagné, on ne gérera pas les semestres, je vais mettre des vrais date et limiter à une plage de un mois.

**Comment by trecouvr** [comment]
Si on veut les stats de ce semestre dans l'etat actuel des choses ca marche pas : Y'a pas A13...

**Comment by mattgu74** [comment]
En même temps il faudrait un vrai module stats non ? :-1: 

Mais bon bref, je suis assigné sur cette issue, je ne l'oublie pas je m'y mettrais dès la semaine prochaine.
