### ISSUE TITLE
Reecriture du service TRESO pour supporter les nouveaux droits

### ISSUE THREAD

**Issue by mattgu74** [payutc/server#184]
C'est insuportable quand on fait la formation des nouvelles fundations de devoir leur expliquer les deux modules de droits, il faut donc migrer le service (et scoobydoo du coup).

**Comment by trecouvr** [comment]
En fait y'a pas de service tréso actuellement, tout est dans AADMIN, du coup il faut en créer un ?

**Comment by mattgu74** [comment]
Oui

**Comment by mattgu74** [comment]
Implémenté dans #343
