### ISSUE TITLE
POSS3 ou VENTEPHYSIQUE

### ISSUE THREAD

**Issue by mattgu74** [payutc/server#185]
Il est urgent d'implémenter un service de vente physique qui utilise les nouveaux droits, pour pouvoir définitivement supprimer l'ancien modèle de droits.

(Et donc l'implémenter dans mozart et pauline)

Je pense que passer par POSS3 est une étape qui vas nous faire perdre plus de temps qu'autre chose, l'écriture de VENTEPHYSIQUE et VENTEWEB proprement en héritant d'une classe commune ServiceVente serait plus productif.

(Et éviterait de recoder deux fois, pauline et mozart)

**Comment by trecouvr** [comment]
Je pense que vu que POSS3 est déjà codé ça va pas nous faire perdre du temps, d'autant plus que pour faire ventephysique et venteweb t'aura juste à copier coller le code fait dans POSS3.

**Comment by mattgu74** [comment]
Je parle de l'implémentation dans Pauline et Mozart.

Il vaut peut être mieux faire les copier/coller maintenant que de se
précipiter sur pauline et mozart, non ?

**Comment by trecouvr** [comment]
Je pense pas. Pour Pauline (et pour mozart ça doit être pareil), y'a trois trucs à faire:
- Changer le endpoint vers POSS3 (les méthodes restent les même, donc à part changer un nom dans une config tout reste pareil)
- Rajouter les méthodes d'interaction avec KEY
- utiliser loginCas et loginApp à la place de loadPos, faire le symétrique pour la deconnexion

Si on liste le travail à faire pour ventephysique:
- Changer le endpoint vers ventephysique, recoder les méthodes si l'API change (y'a pas de raison mais sait-on jamais)
- Rajouter les méthodes d'interaction avec KEY
- utiliser loginCas et loginApp

Donc concrétement que ça soit POSS3 ou autre chose c'est pareil, tout le travail effectué sur les clients ne sera pas à refaire lorsque les nouveaux services seront prêts. Je dirai même plus : l'utilisation de POSS3 peut permettre de faire un palier interessant car si on se bouge c'est déployé la semaine prochaine et on pourra avoir un retour sur experience réel lors des ventes de la semaine des finaux.

**Comment by mattgu74** [comment]
moai bon mozart on a le temps, le pic ferme jeudi et ne rouvre pas avant
2014 donc on aura tout le temps de s'en occuper cet été et en attendant on
peut laisser POSS2 tourner en // de POSS3.

Mais ok ton argument de palier me va, je vais donc me mettre a relire
poss3, tu valides que pour toi elle est prete à merge ? (Tu as codé un
client qui l'utilise ?)

**Comment by mattgu74** [comment]
Actualisation: POSS3 est en cours d'implémentation sur pauline par @trecouvr 

Pour mozart, on verra mais il en est à deux générations de services en retard... (Il est encore en soap, n'est pas pas passé au json-client, et gère encore moins les exceptions...)
Portage prévu dans l'été, mais non prioritaire, car il devrait rester inutilisé pendant les prochains 6 mois.

**Comment by trecouvr** [comment]
Actualisation: Pauline utilise POSS3 depuis fin Juin 2013
