### ISSUE TITLE
Souci CAS

### ISSUE THREAD

**Issue by apuyou** [payutc/server#204]
Petit problème avec le CAS : 
- aller sur casper et se logguer
- aller sur scoobydoo (bizarrement il demande de se logguer à nouveau)
- aller sur casper

Et on se retrouve alors avec la charte.

**Comment by mattgu74** [comment]
A vérifier lors de la mise en Prod de cette semaine, mais je n'ai plus ce bug sur mon install de dev alors que je l'avais lors de l'ouverture de l'issue. Le problème à peut être été résolu inconsciemment.

**Comment by trecouvr** [comment]
Pas de probleme sur payutc_dev, probablement fixé par #265

**Comment by apuyou** [comment]
Je n'ai jamais eu le souci sur dev, mais il ne semble plus présent en production non plus donc on peut dire que c'est bon en effet :)
