### ISSUE TITLE
MessageUpdateFailedException

### ISSUE THREAD

**Issue by apuyou** [payutc/server#211]
Il me semble que `MessageUpdateFailedException` (utilisée [là](https://github.com/payutc/server/blob/b25939d8054e146799c04d023859f7c26ab7385a/src/Payutc/Bom/MsgPerso.php#L65) et [là](https://github.com/payutc/server/blob/5f6a62ff82d38a01abe116c93a1df2127fcff8c3/class/User.class.php#L273)) n'est définie nulle part.

Il faut créer le fichier dans le dossier Exception.

**Comment by mattgu74** [comment]
@alecalve

**Comment by apuyou** [comment]
Closed in #212
