### ISSUE TITLE
Gestion des paniers

### ISSUE THREAD

**Issue by mattgu74** [payutc/server#221]
Ceci est un pré-requis au développement de vente web. Implémenter une table "transactions" permettant de grouper plusieurs "purchases".

Cela n'implique pas de nouveaux services.

**Comment by apuyou** [comment]
Est-ce que je laisse les annulations par produit, ou bien je les fait par panier aussi ?

**Comment by mattgu74** [comment]
Dans moneywin c'était insupportable de ne pas pouvoir annuler item par item
et de devoir tout refaire...

Mais après pouvoir quand tu passes le badge sur mozart, voir une liste de
panier, et pouvoir au choix annuler le panier ou les items pourrait être
bien.

En tout cas il ne faut pas casser le fonctionnement actuel il est plus
pratique que d'annuler tout le panier et revendre les produits réellement
acheté.

Mais tu peux ajouter une méthode "cancelPanier" qu'on implémentera un jour
ou l'autre dans mozart.

Qu'en penses tu ?

**Comment by apuyou** [comment]
Je ne vais pas ajouter une méthode "pour plus tard", c'est pas mon genre ^^

Donc je laisse comme actuellement, annulation par article, ça me paraît plus pratique aussi :)

**Comment by apuyou** [comment]
Done dans #283
