### ISSUE TITLE
Affichage des messages d'erreur

### ISSUE THREAD

**Issue by apuyou** [payutc/server#23]
`getErrorDetails` renvoie encore du CSV. Qui utilise encore ça dans les clients ?

Le client a déjà le code d'erreur, une string du type _Titre : Message d'erreur_ me paraît largement suffisante.

C'est extrêmement moche dans casper.

**Comment by mattgu74** [comment]
Normalement tout les clients qui utilise la fonction getErrorDetails ;)

 (un git grep dans les dépots clients sur getErrorDetails devrait vite répondre à ta question ^^)

**Comment by apuyou** [comment]
Ben casper gère ça comme une chaîne de caractères dans le cas des virements.

C'est juste que ça n'avait jamais été testé vu qu'il y avait le souci de l'utf8 ^^

**Comment by apuyou** [comment]
Corrigé dans https://github.com/payutc/casper/pull/7

Il faut quand même vraiment uniformiser la gestion des erreurs, mais c'est l'objet de #34.
