### ISSUE TITLE
Virement qui n'apparait pas dans l'historique

### ISSUE THREAD

**Issue by mattgu74** [payutc/server#250]
En faisant des tests sur mon install de dev, j'ai du virer de l'argent pour pouvoir recharger de l'argent.

Et j'ai constaté que le virement en question n'apparaissait pas dans mon historique.
- J'ai fait un test avec d'autres virements qui eux apparaissent.
- J'ai été vérifié dans la base de données, le virement est bien effectif.
- Le problème semble donc venir de mon message sur le virement `vide mon compte, pour pouvoir recharger ;)`

Est-ce la longueur ou les caractères spéciaux ? Le problème vient-il de casper ou du serveur ?

Plan d'action attendu:
- [x] Ecriture d'un test qui vérifie si le problème vient du serveur ou non. (Du coup écriture d'un test qui échoue)
- [x] Correction du bug pour que le test passe (coder #251)

**Comment by apuyou** [comment]
Ouais à tous les coups c'est le `;` vu que y'a du CSV partout dans les `ComplexData`.

**Comment by trecouvr** [comment]
Fixed in #265 (casperv2)
