### ISSUE TITLE
Réécriture du service MADMIN

### ISSUE THREAD

**Issue by mattgu74** [payutc/server#251]
`MADMIN` est l'un des derniers services qui : 
- [x] a encore des requetes sql écrites dedans
- [x] n'utilise pas la connection d'application (loginApp)
- [x] utilise encore les `complexData` qui cause le bug #250

**Comment by mattgu74** [comment]
Linked to #31 et #40

**Comment by trecouvr** [comment]
MADMIN a disparu avec tous les problèmes cités depuis #265 (casperv2)
