### ISSUE TITLE
Ajouter le user_id et le app_id dans les logs.

### ISSUE THREAD

**Issue by mattgu74** [payutc/server#252]
Etant donné que `user_id` et `app_id` sont stockés en variable de session, on pourrait demander à la classe Log de les ajouter automatiquement aux logs comme elle le fait avec la date.

Globalement quand un log d'erreur ou de warning apparaît, ça peut toujours être utile de savoir à qui c'est arrivé et sur quelle application.

Actuellement on l'a quasiment oublié de tous les logs qu'on a fait... (Parce que c'est long et fastidieux de réécrire tout le temps la même chose...) Du coup si on le forçait au niveau supérieur ce serait cool.

PS: Avant de coder cette issue, merci d'attendre qu'elle soit validé, cette issue est ouverte aux discussions. @trecouvr @apuyou Qu'en pensez-vous ?

**Comment by apuyou** [comment]
Ça me paraît très bien :)

**Comment by trecouvr** [comment]
On a créé une surcouche au loger c'est parfait pour ce genre de cas
