### ISSUE TITLE
VENTEWEB

### ISSUE THREAD

**Issue by mattgu74** [payutc/server#253]
`VENTEWEB` est un nouveau service qui doit permettre aux associations de faire payer par payutc via internet.

L'exemple principal c'est des billetteries (Etuville, Comet, Skiutc).
ça peut aussi être des ventes de panier cac'carotte.

Pour certain montant (je pense au billet d'Etuville ou des voyages skiutc) il faut directement rediriger la personne pour qu'elle paie le montant directement.
Pour d'autres comme des billets Comet il faut prélever sur le compte payutc. Si le solde du compte payutc est trop faible, il rediriger la personne sur le système de paiement mais en demandant un rechargement au passage pour faire minimum 10€.

**Comment by trecouvr** [comment]
On stock un truc dans la db quand c'est une vente directe ? On autorise les utilisateurs non inscrits sur payutc ?

**Comment by mattgu74** [comment]
OUI

## 

Matthieu GUFFROY

2013/10/4 Thomas Recouvreux notifications@github.com

**Comment by trecouvr** [comment]
On stock quoi dans la db du coup ?

**Comment by apuyou** [comment]
Fait dans #286 

Pour répondre à la question de Thomas, on a rajouté une colonne `tra_id` dans la table `t_paybox_pay`.
- Si `usr_id` est présent, c'est un rechargement. À l'issue du paiement CB, il faut créditer le compte de l'utilisateur.
- Si `tra_id` est présent, c'est une transaction. Dans ce cas, si `usr_id` est présent, c'est débité de son compte (qu'on vient de recharger), sinon on vérifie que le montant correspond à la transaction `tra_id` et on la valide.
