### ISSUE TITLE
Classe CAS

### ISSUE THREAD

**Issue by apuyou** [payutc/server#264]
Réécrire la classe pour le CAS en PSR-0, sans la dépendance pour le XML et en utilisant Curl au lieu de file_get_contents (pour une meilleur gestion des erreurs).

**Comment by trecouvr** [comment]
Je préfererai utiliser un truc plus haut niveau, à voir si ca peut faire l'affaire http://phphttpclient.com/.
C'est quoi que tu appelles la dépendance pour le xml ?

**Comment by apuyou** [comment]
Ça : https://github.com/payutc/server/blob/master/class/xmlToArrayParser.class.php

Dans PHP5 il y a un truc natif mieux.

Je suis chaud pour utiliser un truc plus haut niveau, l'API de Curl est vieille...
