### ISSUE TITLE
Logs de Payline

### ISSUE THREAD

**Issue by apuyou** [payutc/server#278]
Il faudrait arriver à les faire passer dans Monolog, car là actuellement il y a deux fichiers log par jour du coup.

**Comment by mattgu74** [comment]
Moai, c'est meme pire que ça...
Moi j'ai deux fichiers de log aussi, mais dans l'ancien je n'ai pas que payline, j'ai toujours ce qui est des logs on va dire supérieur au level "info".

Et j'ai un nouveau fichier qui vient dans le dossier web (j'aimerais bien savoir pourquoi d'ailleurs ?) et qui ne semble contenir que les logs de niveau `debug`...

Bref c'est l'anarchie... @trecouvr  tu nous expliques ?

**Comment by trecouvr** [comment]
Avant le nouveau system de log, les logs étaient écrit par chance dans le meme fichier que payline. Peut etre que tu n'a pas supprimé les anciens logs. Pour les logs dans web c'est bizar je t'avoue ^^

**Comment by apuyou** [comment]
Comment je dois faire pour avoir les logs debug ?

**Comment by trecouvr** [comment]
https://github.com/payutc/server/blob/master/config.inc.dist.php#L74 quand tu met dev ca va activer le debug. Tu as 3 modes : DEV, PRD, et TST.

**Comment by apuyou** [comment]
Avec DEV j'ai pas le debug, je vais essayer TST.

**Comment by trecouvr** [comment]
Avec DEV tu devrais avoir le debug, TST c'est utilisé seulement lors des tests, il faut pas que tu l'utilises en temps que developpeur.
