### ISSUE TITLE
Documenter le processus de WEBSALE

### ISSUE THREAD

**Issue by mattgu74** [payutc/server#288]
De manière à faciliter l'adoption par les associations du module permettant d'encaisser de l'argent par internet. Il faudrait documenter notre api et expliquer comment ça fonctionne.

**Comment by trecouvr** [comment]
Un lovely chart c'est cool, sinon Dia ca passe aussi c'est juste que les dessins seront plus moches.

**Comment by apuyou** [comment]
Là il faut surtout utiliser https://www.websequencediagrams.com à mon avis :)

**Comment by trecouvr** [comment]
Ah ouai y'a celui là aussi qui est cool. Ca sera parfait un diagramme de séquence.

**Comment by trecouvr** [comment]
Faudrait ajouter à ça une doc sur les différents états d'une transaction et ce qu'ils signifient.

**Comment by apuyou** [comment]
https://github.com/payutc/server/wiki/Web-Payment
