### ISSUE TITLE
Gestion des réductions

### ISSUE THREAD

**Issue by apuyou** [payutc/server#298]
Pour le Polar, il faudrait pouvoir que le client spécifie un % de réduction avec une ligne d'une transaction, qui serait retirée du sous-total.

**Comment by trecouvr** [comment]
On stock dans la db la reduc ? 
Pour rappel la table purchase ressemble actuellement à ça : 
tra_id
obj_id
pur_qte
pur_unit_price
pur_price
pur_removed

**Comment by apuyou** [comment]
Pour moi : 
- la réduction va dans une colonne `pur_reduction` (un float)
- la colonne `pur_unit_price` ne change pas
- la colonne `pur_price` est calculée avec la réduction

**Comment by mattgu74** [comment]
La réduction est donc passé par le client ? De manière à éviter les erreurs, ne faudrait-il pas pouvoir configurer pour chaque article la réduction maximale ?

**Comment by apuyou** [comment]
Ça me paraît lourd comme option, si on fait confiance au client pour dire s'il doit y avoir réduction ou non (quel que soit le montant), alors on lui fait confiance pour gérer ça sans erreurs...

**Comment by feuloren** [comment]
Je m'occupe de ça,
il faut que je garde la compatibilité avec quels clients ?

**Comment by apuyou** [comment]
Tous ?

J'ai un doute en fait, est-ce qu'on peut avoir des paramètres facultatifs ?

Si oui c'est ça qu'il faut faire, sinon est-ce qu'on modifie POSS3 ou bien on fait une méthode `transactionWithReduc` ?

**Comment by trecouvr** [comment]
On peut faire des paramètres optionnels. JSON dispatcher le gère très bien, pour le soap je crois qu'il met bull si tu donnes pas de parametre

**Comment by feuloren** [comment]
Y a pas besoin de paramètre optionnel, le paramètre obj_id est un chaîne de caractère.

**Comment by feuloren** [comment]
Fait dans #305
