### ISSUE TITLE
Config apache .dist

### ISSUE THREAD

**Issue by trecouvr** [payutc/server#3]
Une config apache a éditer pour faire tourner le serveur en local.
Un petit dossier config avec un README dedans.

**Comment by apuyou** [comment]
La config est tout ce qu'il y a de plus standard, les trucs particuliers sont dans le `.htaccess`.

Je pense que c'est plus simple que les gens mettent chaque application dans leur `/var/www` plutôt que de fournir un fichier avec un `<VirtualHost>` et d'avoir à modifier des réglages du système.
