### ISSUE TITLE
Nettoyage source

### ISSUE THREAD

**Issue by apuyou** [payutc/server#31]
Il y a des espaces en fin de lignes, au moins dans le fichier `AADMIN.class.php`.

Il faudrait tous les retirer dans un commit unique.

**Comment by ptbrowne** [comment]
Maintenant c'est fait non ? Dans mon commit qui a enlevé les espaces, j'ai
indiqué avec les commentaires ou était la "vraie" modif. Maintenant ya plus
d'espace, pas besoin de faire un commit dedié si ?

2012/11/20 Arthur Puyou notifications@github.com

**Comment by apuyou** [comment]
Ben c'est toujours bien de faire des commit séparés pour chaque truc...
Mais après c'était surtout pour le faire à part sur les autres fichiers et
éviter que le problème ne se reproduise.

Florent a fait un script pour ça.

Arthur Puyou

2012/11/21 Patrick Browne notifications@github.com

**Comment by ptbrowne** [comment]
Oui oui je sius d'accord de faire des commits separés :) Mais là j'avais
pas vu que mon éditeur l'avait fait tout seul donc j'ai la flemme de revert
les modifications et de faire deux commits separés. J'ai desactivé la
fonctionnalité dans mon éditeur.

2012/11/21 Arthur Puyou notifications@github.com

**Comment by apuyou** [comment]
Ouais nan t'embêtes pas pour cette fois ;)

Arthur Puyou

2012/11/21 Patrick Browne notifications@github.com

**Comment by mattgu74** [comment]
Je propose que ce ticket soit effectué à la fin de la milestones "Fin P13".

On fait passer un script pour nettoyer notre code à la fin de nos développements du semestre.
Et avoir un truc tout beau tout propre.

**Comment by mattgu74** [comment]
Cette issue sera fermable après la suppression des services "deprecated" POSS2/AADMIN/MADMIN

**Comment by apuyou** [comment]
POSS2, AADMIN et MADMIN ont été supprimés
