### ISSUE TITLE
Erreurs PHP

### ISSUE THREAD

**Issue by apuyou** [payutc/server#32]
```
[Tue Nov 20 23:42:02 2012] [error] [client 192.168.144.41] PHP Fatal error:  Call to a member function getFirstname() on a non-object in /usr/share/buckutt/server/AADMIN.class.php on line 134
```

as well as

```
[Tue Nov 20 14:50:10 2012] [error] [client 192.168.144.17] PHP Fatal error:  Call to a member function getFirstname() on a non-object in /usr/share/buckutt/server/MADMIN.class.php on line 251
```

**Comment by apuyou** [comment]
Je n'ai plus les erreurs précédentes, par contre il y a ça récemment, lié au virement dans casper :

```
[Fri Feb 22 10:20:46 2013] [error] [client 79.82.18.4] PHP Fatal error:  SOAP-ERROR: Encoding: string 'K\\xe9...' is not a valid utf-8 string in /usr/share/buckutt/casper/virement.php on line 5, referer: https://assos.utc.fr/payutc/
[Fri Feb 22 10:20:46 2013] [error] [client 79.82.18.4] PHP Fatal error:  Uncaught SoapFault exception: [Client] SOAP-ERROR: Encoding: string 'K\\xe9...' is not a valid utf-8 string in /usr/share/buckutt/casper/virement.php:5\nStack trace: \n#0 /usr/share/buckutt/casper/virement.php(5): SoapClient->__call('getRpcUser', Array)\n#1 /usr/share/buckutt/casper/virement.php(5): SoapClient->getRpcUser('K?vin SCHEIB')\n#2 /usr/share/buckutt/casper/index.php(6): require('/usr/share/buck...')\n#3 {main}\n  thrown in /usr/share/buckutt/casper/virement.php on line 5, referer: https://assos.utc.fr/payutc/
```

**Comment by mattgu74** [comment]
Je pense que la méthode getRpcUser (qui si je ne dis pas de connerie permet de faire l'autocomplétion sur les users lors du virement) et à virer. Elle est non performante et non sécurisé... Il faudrait exposer du json et limiter le nombre d'utilisateur renvoyé (ou tant que le retour est > 10, alors on renvoit rien et on laisse l'user continuer à écrire)

**Comment by mattgu74** [comment]
C'est réglé ça non ?

**Comment by apuyou** [comment]
Non, c'est un bug dans MADMIN qui ne vérifie pas si le User est null ou pas
avant d'appeler des méthodes dessus.

**Comment by mattgu74** [comment]
Dans ce cas, tu peux mettre cette tache en "waiting on" du fait de venir
mettre la nouvelle gestion des droits.
Etant donné que la fonction qui gère les droits s'assure d'avoir un user
chargé ça fera "la correction" tout seul.

## 

Matthieu GUFFROY

Président du SiMDE assos.utc.fr/simde
http://wwwassos.utc.fr/simdePrésident de SkiUTC 2013
Responsable informatique du Pic'asso (Foyer étudiant)
Responsable de la billetterie en ligne de l'utcéenne assos.utc.fr/etuville
Etudiant ingénieur en génie informatique
Université de Technologie de Compiègne

2013/3/30 Arthur Puyou notifications@github.com
