### ISSUE TITLE
Déléguer la gestion des infos users à ginger

### ISSUE THREAD

**Issue by apuyou** [payutc/server#33]
Il est inutile de faire une copie de l'information dans payutc. Un seul appel à ginger peut nous donner toutes les infos dont on a besoin lors d'une transaction, sans souci de synchro :
- UID de badge
- Mineur/majeur
- Cotisant/non-cotisant

**Comment by apuyou** [comment]
Pour cotisant et majeur/mineur, c'est dans #49.

**Comment by mattgu74** [comment]
C'est fini ça non ?

**Comment by apuyou** [comment]
Non, mineur/majeur et le statut cotisant sont délégués, mais pas le badge.

J'ai complètement réécrit la classe User pour ça, j'ai pas mal avancé dans l'Eurostar l'autre jour.

**Comment by apuyou** [comment]
Fixed in #216
