### ISSUE TITLE
Solde des fundations

### ISSUE THREAD

**Issue by mattgu74** [payutc/server#330]
Ajouter une colonne 'fun_solde' dans la table 't_fundation_fun' représentant le solde encaissé et non reversé à la fundation.

**Comment by feuloren** [comment]
Et tu le modifies à chaque transaction validée ?
la fonction getRevenue dans stats fait déjà ça, et plus si besoin.

Le 12 mars 2014 15:25, Matthieu Guffroy notifications@github.com a écrit :

> Ajouter une colonne 'fun_solde' dans la table 't_fundation_fun'
> représentant le solde encaissé et non reversé à la fundation.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/payutc/server/issues/330
> .

## 

Florent Thévenet
Étudiant Ingénieur UTC - Génie Informatique
Président du Polar UTC
06.63.46.92.46

**Comment by mattgu74** [comment]
Moép enfait je suis un peu dans le flou dans ma tête ^^

Je suis entrain de voir pour améliorer la partie gestion administrative de
payutc (en terme de reversement d'argent aux assos).

Et du coup, il y'a non seulement l'argent de l'assos, mais il y'a l'argent
déjà reversé et donc l'argent de l'assos.
Non seulement ça permet de diminuer la compléxité de la requete et évite de
recalculer en permanence le solde des fundations, mais enfait j'ai aussi
une petite vision d'avenir de ce qu'on pourrait faire avec payutc (Le
paiement entre les assos).

Genre les petites assos qui tiennent des perms, pourrait se voir reverser
leur benef sur payutc et payer leur facture au polar via payutc.
Il y'a des assos comme ça qui se facture des services, elle pourrait payer
entre elles via payutc.

De même les petites notes de frais qu'on certains membres d'assos, genre en
faisant des courses pour préparer une perm au pic, pourraient être
remboursés directement par l'assos sur leur compte payutc...

**Comment by mattgu74** [comment]
Je ferme cet issue, le solde est actuellement calculé et affiché via le Service TRESO et ça marche très bien.
