### ISSUE TITLE
Ajouter un parametre de config url ginger

### ISSUE THREAD

**Issue by trecouvr** [payutc/server#38]
Il faudrait un paramètre dans la config pour pouvoir préciser l'url de Ginger, comme celà il serait possible de donner un ginger local pour les tests.

**Comment by mattgu74** [comment]
En plus il GingerClient prend en paramètre l'url dans son constructeur...
Ce n'est pas très long à ajouter à tout casse le pull request fera 1ligne (la conf) + 1lignes par création d'objet GingerClient... Donc bon allez 5lignes ^^

**Comment by apuyou** [comment]
Oui, c'est moi qui ai écrit ginger-client ^^ 

En fait je ne l'ai pas fait parce que dans la situation actuelle, il y a plusieurs appels à Ginger, donc il faudrait mettre le paramètre à plusieurs endroits. Alors c'est pas super compliqué, mais ça fait plus d'une ligne de code.

En bref, depends on #33
