### ISSUE TITLE
Gestion des permissions

### ISSUE THREAD

**Issue by apuyou** [payutc/server#39]
Il faut refaire la gestion des permissions, en distinguant (deux tables séparées) :
- les permissions User/Fundation
- les permissions Fundation/POS

Chaque droit serait un nom sur 6 caractères.

Et il faut une classe bien faite pour gérer tous ces droits.

**Comment by mattgu74** [comment]
Ce ticket duplique les taches récemment créé concernant le nouveau système de droit #58 #57 #56 ...
