### ISSUE TITLE
loadPos for apikey or login/password

### ISSUE THREAD

**Issue by trecouvr** [payutc/server#4]
It would be great to be able to load the pos with an apikey or a login/password pair, especially for dev.

**Comment by apuyou** [comment]
Une sorte de CAS local, qui renvoie un ticket toujours valide sans te demander de mot de passe, est-ce que ça répond à ta demande ?

**Comment by mattgu74** [comment]
Il a toujours été hors de question d'introduire une backdoor, les méthodes d'auth doivent être les mêmes en dev qu'en prod, sinon on risque d'en laisser passer en pushant sur la prod.

Pour la connection "user", un faux cas est disponible depuis quelque jours:
https://github.com/payutc/faux-cas

Du coup je ferme le ticket.
