### ISSUE TITLE
Retirer le SQL des frontales

### ISSUE THREAD

**Issue by apuyou** [payutc/server#40]
- [ ] Remplacer toutes les requêtes sql dans les frontales par des appels aux BOM
- [ ] Retirer les méthodes obsolètes des BOM

**Comment by mattgu74** [comment]
- [x] Propel ayant été abandonné, ce ticket part à la poubelle ? (enfin son titre tout du moins ?)

**Comment by mattgu74** [comment]
Penser à #158 au moment du déplacement des requêtes.

**Comment by apuyou** [comment]
Il n'y a plus de SQL dans les services. Le SQL pas encore en Dbal qui reste dans les autres classes sera traité dans #158
