### ISSUE TITLE
Utiliser un contrôleur pour les frontales

### ISSUE THREAD

**Issue by apuyou** [payutc/server#44]
Plutôt que d'arriver directement sur les frontales, il faut un unique point d'entrée qui instancie la classe correspondante. Ceci permet de faire le bootstrap à un seul endroit, et permettra aussi de supporter des requêtes REST sans changer la classe (vu qu'il n'y aura plus le `wsdl.inc.php` à la fin de chaque classe).

Sur ginger, on utilise http://www.slimframework.com qui est très bien pour ça.

**Comment by trecouvr** [comment]
Done in #67
