### ISSUE TITLE
[reversement_argent] Ajouter les informations bancaires des fundations

### ISSUE THREAD

**Issue by mattgu74** [payutc/server#46]
Pour faciliter le travail de l'interface de rechargement, il est intéressant de pouvoir attacher à chaque fundation, ces informations de reversement (RIB par exemple).
Comme ça le trésorier suprême, au moment ou l'interface lui demander de reverser X d'argents à la fundation Y, il peut retrouver le RIB de l'assos facilement.

Cette feature, peut s'avérer pratique, mais n'est pas forcément nécessaire.

**Comment by apuyou** [comment]
Quand tu ajoutes un RIB dans Progeliance, tu es obligé de l'enregistrer (après l'avoir validé avec le téléphone et tout). Du coup je pense que l'intérêt est plutôt limité.

Et ça nous fait stocker des données bancaires, je ne sais pas si on peut faire ça comme ça.
