### ISSUE TITLE
Pied de ticket par défaut

### ISSUE THREAD

**Issue by apuyou** [payutc/server#52]
Pouvoir stocker le pied de ticket par défaut pour chaque fundation, avec une méthode pour le récupérer dans POSS2 et une pour le modifier/récupérer dans AADMIN

**Comment by apuyou** [comment]
Il faut faire une table tickets pour les stocker, avec :
- utilisateur (pouvant être NULL)
- fondation (pouvant être NULL)
- message

Et prendre le message répondant au plus de critères possibles (utilisateur+fondation, puis utilisateur, puis fondation, puis celui par défaut).

**Comment by mattgu74** [comment]
Qui s'y colle ? Je suis chaud pour faire #69, mais faut que quelqu'un fasse ce ticket d'abord ;)

**Comment by apuyou** [comment]
Je suis assigned a priori :P

**Comment by mattgu74** [comment]
UP ?

**Comment by apuyou** [comment]
Les modifs sur AADMIN n'ont pas été faites, donc c'est pas fini.

**Comment by mattgu74** [comment]
Bah nan, l'interface c'est #69, qui n'attend plus rien de ce ticket. 
Les pied de ticket par défaut sont géré dans #111 et ça a été mergé. Donc pour moi ce ticket et terminé.

Et #69 n'a plus a attendre celui la.

**Comment by mattgu74** [comment]
@alecalve on en est ou de l'implémentation dans scoobydoo de la gestion du pied de ticket pour que les fondations puissent personaliser les messages ?

**Comment by alecalve** [comment]
Le service MESSAGE est prêt et je me bat avec scoobydoo pour faire un module

**Comment by mattgu74** [comment]
@alecalve des nouvelles ?

**Comment by alecalve** [comment]
J’ai eu des vacances et une rentrée chargées, mais je m’y remets dès que possible. En plus j’avais presque fini …

**Comment by mattgu74** [comment]
@alecalve : Avec la réouverture prochaine du pic, ce serait bien de terminer ce que tu as commencé, je suis sur qu'il ne manque pas grand chose.

**Comment by alecalve** [comment]
fait dans #316
