### ISSUE TITLE
Identifier les POS avec une clé unique

### ISSUE THREAD

**Issue by apuyou** [payutc/server#53]
Il faut ajouter une clé secrète dans chaque POS pour l'identifier de manière unique dans le serveur.

Cf. https://github.com/buckutt/BuckUTT_depreciated/issues/33

**Comment by mattgu74** [comment]
Après #57, il faudra créer une clef d'api pour chaque service existant et les insérer dans leurs codes.

**Comment by mattgu74** [comment]
Finalement ceci sera géré par le système de clefs d'application que je suis entrain de faire...
Du coup ce ticket duplique une tache en cours... Je le ferme donc.
