### ISSUE TITLE
Gestion des quantités

### ISSUE THREAD

**Issue by mattgu74** [payutc/server#61]
Actuellement, il y'a une ligne par article vendu, il faudrait pouvoir gérer les quantités (notamment pour le polar qui pourrait vendre par exemple X impressions avec X une valeur pouvant atteindre plusieurs centaines...) 

Cette tache est historiquement assigné à @fthevenet, qui devait l’implémenter pour le polar ^^ (Florent on t'attend :) )

**Comment by feuloren** [comment]
https://github.com/payutc/server/issues/232
Mergé !

**Comment by apuyou** [comment]
J'ai jeté un coup d'œil à #232 et ça me semble très bien :)

À vue de nez comme ça, il manque quand même avant de pouvoir l'utiliser (tu y as surement pensé @feuloren, mais je les note au cas où) : 
- afficher les quantités dans casper
- afficher les quantités dans le CA (on est d'accord que le prix par ligne devrait déjà être bon)

Et pour plus tard : 
- gérer les quantités dans mozart
- gérer les quantités dans pauline

**Comment by mattgu74** [comment]
Grâce à @feuloren et à #232 Le serveur gère maintenant les quantités, c'est donc une issue terminé.
