### ISSUE TITLE
Interface pour changer son pied de ticket

### ISSUE THREAD

**Issue by apuyou** [payutc/server#69]
Pour changer son propre pied de ticket soi-même, laisser une méthode permettant de le faire dans MADMIN (mais sans l'utiliser dans casper).

Voir aussi #52

**Comment by apuyou** [comment]
@alecalve a déjà fait une interface pour modifier le pied de ticket dans la table `users`, il reste à l'adapter quand #52 aura été fait.

**Comment by mattgu74** [comment]
Le label "waiting on" c'est pour quoi ? C'est en attente de quoi cette issue ?

**Comment by apuyou** [comment]
En attente de #52

**Comment by apuyou** [comment]
Fait dans #87
