### ISSUE TITLE
ServiceBase : loginCas

### ISSUE THREAD

**Issue by mattgu74** [payutc/server#77]
Il faudrait retourner des vraies Exceptions.

**Comment by mattgu74** [comment]
En fait Thomas, je ne t'avais pas assigner pour rien, je suis preneur de ta pull-request pour voir les "good practices" et savoir ou est comment déclarer les Exceptions que l'on doit renvoyer.

Parce que moi depuis le début je fait throw/raise Exception("Mon message");   (excuse le throw/raise à force de coder en python/javascript/php je ne sais plus lequel va ou ^^) 

Mais bref, c'est un exemple simple qui sera cool pour montrer à tout le monde comment il faut faire. Moi je vais le faire mal et tu vas râler, mais si tu ne nous montres pas un jour... Comment veux-tu qu'on suives les bonnes règles ^^ Du coup je te réassigne :)

**Comment by trecouvr** [comment]
Batard ! ^^
