### ISSUE TITLE
Passe-partout service dans les droits

### ISSUE THREAD

**Issue by apuyou** [payutc/server#95]
Dans la table des droits, le passe-partout pour les services est `"ALL"`. Partout ailleurs, on utilise `NULL`.

https://github.com/payutc/server/pull/91/files#r3502808

Why ? :confused:

**Comment by mattgu74** [comment]
Enfait on utilise nul part ailleurs NULL ... (enfin pour tout ce qui est droit) 

NULL était effectivement la première idée, mais je ne la sens pas trop.

**Comment by mattgu74** [comment]
Bon suite au début d'utilisation des NULL pour les fun_id ou j'ai finalement utilisé "NULL" dans les communications.

Il faut passer par 0 ou -1 dans les communications et stocker des vrais NULL dans la db.

ça implique de revoir dev_structure.sql pour autoriser le champ service dans les tables de droits à être à NULL et revoir 2/3 requetes sql. + revoir deus trois passages de parametres entre scoobydoo et ADMINRIGHT.

r8 étant décalé à demain je m'assigne cette tache pour demain soir. 

Cela fait suite aux remarques de @apuyou sur #140
