### ISSUE TITLE
POSS2->loadPos without CAS

### ISSUE THREAD

**Issue by trecouvr** [payutc/server#98]
Trouver un moyen de load sans CAS pour les unittests.

**Comment by mattgu74** [comment]
Tu peux pas faire les unittest avec faux cas ? (Même une version encore
mieux qui ne demande rien et autoload un login)
Le 24 mars 2013 13:49, "Thomas Recouvreux" notifications@github.com a
écrit :

**Comment by trecouvr** [comment]
Bah j'aimerai ne pas être dépendant d'un serveur web ni d'une config local...

**Comment by mattgu74** [comment]
Hum je ne suis pas sur de comprendre ce que tu veux faire.
Mais dans tous les cas on ne peut pas mettre de "backdoor" c'est trop dangereux si on l'oublie à la mise en prod.

De toute façon fais toi pas chier avec POSS2, on va la jarter en récrivant bien les services de ventes (tu vas kiffer mon idée) et je suis sur que comme elle sera bien mieux écrite tu pourras la tester comme tu en as envie.

**Comment by mattgu74** [comment]
Je close l'issue, parce qu'elle ne sera jamais réalisé en tant que tel.
1. Cette classe sera bientôt deprecated. Il n'est donc pas prévu d'updater POSS2 avec de nouvelles fonctionnalités.
2. Il n'y aura jamais de backdoor (c'est trop risqué de l'oublier un jour en passant en prod), les services impliquent des users loggués. Donc pour tester, il te faut un faux-cas qui valide tout.
3. Les services ne faisant que rappeler les fonctions de classes qui elle devrait être très bien unittester. Le simple fait d'écrire un test qui "charge le code php" (= instancie) un service, pour s'assurer qu'il n'y a pas d'erreur de syntaxe devrait être suffisant.
4. ....
